### ISSUE TITLE
Procurement

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#15]
## Description

Tenders are the individual contracts or proposals that have been put out to invite bids from companies or organisations that want to provide goods and services for an activity.

Contracts are the individual contract(s) signed with a company, organisation or individual that provides goods and services for the activity.

These can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

## Proposed tests

Tender is present
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02, B02 or G01
    And `transaction/aid-type/@code` is not any of A01, A02 or B02
    Then `document-link/category[@code="A10"]` should be present
```

Contract is present
```python  
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02, B02 or G01
    And `transaction/aid-type/@code` is not any of A01, A02 or B02
    Then `document-link/category[@code="A06"] | document-link/category[@code="A11"]` should be present
```

**Comment by breidertmt** [comment]
How will PWYF plan to take into account activities which have been redacted due to sensitivities for the health and safety of implementing partners or national security risks/interests, especially in light of the current situation in Afghanistan. The U.S. has standard redaction language which is used and allowable by law and it is in line with OECD/DAC decisions and to protect the security of our implementing partners, programs, and beneficiaries. The U.S. and other donors redact titles, descriptions, and implementing partner names (with the exception of PIOs) for Afghanistan and other sensitive areas e.g. Burma.  We are working internally with USG guidance and externally both with IATI and through our DAC delegate to establish guidance and best practices on how to move forward to balance transparency and sensitive data.

**Comment by publishwhatyoufund** [comment]
**@breidertmt**: publishers will not be penalised for security-related redactions in our IATI data quality sampling, and redacted documents or redaction text will be picked up and scored by our automated tests.
