### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#16]
## Description

The title of the activity is the name of the activity. This is preferably the formal name of the activity, but does not have to be.

## Proposed test

Title is present
```python
   Given an IATI activity
    And the activity is current
    Then `title[text() or narrative/text()]` should be present
```
 
Title has at least 10 characters
```python
   Given an IATI activity
    And the activity is current
    Then `title/text() | title/narrative/text()` should have at least 10 characters
 ```

**Comment by breidertmt** [comment]
How will PWYF plan to take into account activities which have been redacted due to sensitivities for the health and safety of implementing partners or national security risks/interests, especially in light of the current situation in Afghanistan. The U.S. has standard redaction language which is used and allowable by law and it is in line with OECD/DAC decisions and to protect the security of our implementing partners, programs, and beneficiaries. The U.S. and other donors redact titles, descriptions, and implementing partner names (with the exception of PIOs) for Afghanistan and other sensitive areas e.g. Burma.  We are working internally with USG guidance and externally both with IATI and through our DAC delegate to establish guidance and best practices on how to move forward to balance transparency and sensitive data.

**Comment by randymatthews** [comment]
We would like to request to consider giving majority of credit for titles that have abbreviations within them.   Titles with abbreviations are more transparent than no title at all.   A deduction for having abbreviations present seems more appropriate that giving no credit at all for titles provided with abbreviations within them.

**Comment by publishwhatyoufund** [comment]
**@breidertmt**: Publishers will not be penalised for security-related redactions in our IATI data quality sampling, and redacted documents or redaction text will be picked up and scored by our automated tests. 

**@randymatthews**: Abbreviations can be included in titles but should be explained. The title should be understandable by someone without prior knowledge of the project.
