### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#17]
## Description

The description of the activity is a meaningful descriptive text, longer than the title, explaining what the activity is.  The description must be at least 80 characters in length.

## Proposed test

Description is present
```python
   Given an IATI activity
    And the activity is current
    Then `description[text() or narrative/text()]` should be present
```

Description has at least 80 characters
```python
   Given an IATI activity
    And the activity is current
    Then `description/text() | description/narrative/text()` should have at least 80 characters
```

**Comment by publishwhatyoufund** [comment]
We are considering an increase to the weighting of the Descriptions indicator from 1 to 3 weighting.

**Comment by breidertmt** [comment]
How will PWYF plan to take into account activities which have been redacted due to sensitivities for the health and safety of implementing partners or national security risks/interests, especially in light of the current situation in Afghanistan. The U.S. has standard redaction language which is used and allowable by law and it is in line with OECD/DAC decisions and to protect the security of our implementing partners, programs, and beneficiaries. The U.S. and other donors redact titles, descriptions, and implementing partner names (with the exception of PIOs) for Afghanistan and other sensitive areas e.g. Burma.  We are working internally with USG guidance and externally both with IATI and through our DAC delegate to establish guidance and best practices on how to move forward to balance transparency and sensitive data.

**Comment by stevieflow** [comment]
> We are considering an increase to the weighting of the Descriptions indicator from 1 to 3 weighting.

This was not flagged in the "tracked changes" Methodology document that was previously made available.  

![2022-Index-Technical-Paper_track-changes-pdf (4)](https://user-images.githubusercontent.com/1209944/134366412-41348689-ecbe-445c-a7bb-a769a1c55b4a.png)

Nor is it in the latest Methodology doc

It would be very helpful if @publishwhatyoufund can provide an updated proposed weightings table, to help understand the various proposed changes

**Comment by Mhirji** [comment]
I am trying to understand the rational around increasing the weight of this indicator, and to be honest its value at all.  From a data perspective, free text fields like titles and descriptions are only useful when looking at activities from a communications perspective, like a report or web page.  If an organization is publishing budget data and results data, one should be able to understand what the program is about from a data perspective which is more relevant to scoring the level of transparency of a given organization.  If the indicator will continue to be measured, if should be done within the context of other elements which better illustrate what an activity is doing rather than some arbitrary text someone or something and entered into a field.

**Comment by stevieflow** [comment]
It is worth noting that for lots of publishers, who have a portfolio of hundreds or _thousands_ of activities, the generation of description text for IATI will be automated, or derived from processes that concatenates data fields together.  This can prove useful, as it provides a summary of the activity - but there is no information as to whether @publishwhatyoufund would consider this process to be _meaningful_.  

As @Mhirji highlights, the multi-faceted nature of outputting IATI data will not readily involve communications - there is not much practice of larger publishers hand-crafting description texts for IATI activities.  Heavier emphasis is on ensuring all financial, documents and results data points can be synthesised into a single, _machine-readable_, activity - which seems in line with the direction of the initiative.  

Is there also a crossover with the https://github.com/pwyf/2022-Index-indicator-definitions/issues/31 indicator here, too?  

> The objectives or purposes of the activity are those that the activity intends to achieve.

We also know that in IATI, a description can be split across [different types](https://codelists.codeforiati.org/DescriptionType/) , which includes Objectives and Target Groups.  The test doesn't extend in to this area.

**Comment by Melina-Loewer** [comment]
**On behalf of BMZ we would like to raise:** Is it planned that the “considering changes” listed on Github for each indicator will also be included in the Technical Paper 2022 currently published on the PWYF website? These changes only mentioned on GitHub mostly concerns the re-weighting of the points per indicator.

**Comment by ForeignCommonwealthDevelopmentOffice** [comment]
FCDO agrees with the concerns raised above by Melina, Stevie and Mhirji, alongside USAID.

**Comment by PierreRichardGavi** [comment]
**on behalf of Gavi:** "Gavi activity descriptions are auto-generated from systems.  The detailed content on objectives and target groups can be found in associated documents, also linked from any activity.  We therefore question the re-emphasis on this indicator, given how it is often produced."

**Comment by cmmarschner** [comment]
MCC agrees wholeheartedly w/ Steven that PWYF needs to clarify what is considered _meaningful_. MCC uses standardized but clear descriptions for specific types of activities such as “audit” but in the past, because they did not reference a specific country, were not considered sufficient. We do derive certain types of descriptions and understanding what is required to pass the 'meaningful' threshold will allow us to improve this process.

**Comment by jzheng-79** [comment]
Please clarify the rationale for increasing weight significantly for this indicator, and currently the proposed change is not included in 2022 ATI methodology paper. UNICEF shares similar concerns as comments above on heavily relying on free-text field, which often times are auto-generated text for publishers with large number of activities.

**Comment by publishwhatyoufund** [comment]
**@breidertmt:** publishers will not be penalised for security-related redactions in our IATI data quality sampling, and redacted documents or redaction text will be picked up and scored by our automated tests.

**@stevieflow, @Mhirji**: the proposal to increase the weighting for Descriptions has emerged since the methodology review and publication of the technical paper. It is based on our experience researching aid given for specific thematic purposes, for which we have used titles and descriptions to identify relevant activities. This experience has shown us the importance of descriptions for identifying project types when policy marking is not sufficient and when use of policy markers by publishers is not consistent. We have also seen the poor quality or lack of usefulness of many descriptions and hope that the increase in weighting will incentivise publishers to improve their activity descriptions. For these reasons we will be increasing the weighting of Description from 1 to 3.

**@stevieflow, @ForeignCommonwealthDevelopmentOffice, @PierreRichardGavi, @cmmarschner, @jzheng-79:** we would expect a description to meaningfully describe what the activity is. This also follows the IATI definition for the description element which states that it is “A longer, human-readable description containing a meaningful description of the activity.” To pass our data quality sampling, at a minimum a description should include a description of what the project intends to do and how it intends to do it (the mode of intervention). If possible, it is also helpful to include information about who the project intends to benefit and where the project will be implemented. Machine generated descriptions that take information from other activity fields and then structures this into text are not considered meaningful since they provide no additional information about the activity. Descriptions that simply repeat the title of the project are also insufficient to pass our manual sampling. Objectives may be included in the description, but they are not always included and are not necessary to pass our descriptions indicator tests. For Indicator 31 we look for specific descriptions of the objectives of the project either from the Objectives text field or from an objectives document. 

**@Melina-Loewer**: yes, we will reissue the Technical Paper and make it available on our website with any changes from this consultation included.

**Comment by publishwhatyoufund** [comment]
This test will be modified by increasing the weighting of Description from 1 to 3.
