### ISSUE TITLE
Sub-national location

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#23]
## Description

The sub-national geographic location is information about where the activity is located within a country.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the activity has been marked with the recipient region code 998 (bilateral/unspecified) - the intention is to exclude activities that do not have any geographic focus.

This is not expected if the default aid type code is administrative costs (G01).

## Proposed tests
Location (sub-national)
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `recipient-region/@code` is not 998
    And `default-aid-type/@code` is not G01, B01 or B02
    Then `location` should be present
``` 
Location (sub-national) coordinates or point
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `recipient-region/@code` is not 998
    And `default-aid-type/@code` is not G01, B01 or B02
    Then `location[coordinates or point]` should be present
```

**Comment by publishwhatyoufund** [comment]
We are considering a change to the weighting of the Sub-national location indicator from 3.5 to 3.

**Comment by ToonVB** [comment]
(Contributions for) activities coded type of aid B03, B04, F and H (and A obviously)  can often not be pointed to a specific location either.
Furthermore, activities are often "nation-wide".
In practice this means we will point to the capital, without it being relevant, isn't that called "noise" ? ;-)

**Comment by breidertmt** [comment]
How will PWYF plan to take into account projects which have been redacted due to sensitivities for the health and safety of implementing partners or national security risks/interests, especially in light of the current situation in Afghanistan. The U.S. has standard redaction language which is used and allowable by law and it is in line with OECD/DAC decisions and to protect the security of our implementing partners, programs, and beneficiaries. The U.S. and other donors redact titles, descriptions, and implementing partner names (with the exception of PIOs) for Afghanistan and other sensitive areas e.g. Burma.  We are working internally with USG guidance and externally both with IATI and through our DAC delegate to establish guidance and best practices on how to move forward to balance transparency and sensitive data.

**Comment by stevieflow** [comment]
> We are considering a change to the weighting of the Sub-national location indicator from 3.5 to 3.

This was not flagged in the "tracked changes" Methodology document that was made available previous (whereas other changes in weighting were)

![2022-Index-Technical-Paper_track-changes-pdf (2)](https://user-images.githubusercontent.com/1209944/134365304-f46d7cd7-6c10-482e-bf81-fbf49d6a8a7a.png)

It would be very helpful to see a proposed overview of the indicator weightings, to understand the impact of these proposals

**Comment by AndieVaughn** [comment]
We propose that aid categories 'A' and 'B' be excluded. In these cases, the reporting organization would not know the exact locations of the activities being that another organization oversees implementation and management. Beyond these categories, there are other examples - such as technical assistance - where the location may not be pertinent. Additionally, IATI’s preliminary guidance on sub-national locations notes that location data should only be added when it is safe to do so and given security concerns in some countries, organizations may (with good reason) choose to not publish locations. With all of these reasons in mind and to better measure transparency, USAID recommends the test score a percentage (80% to 90%?) of their activities with location data to receive a full score.

**Comment by Mhirji** [comment]
Fully agree with @ToonVB , we operate at a national, and in some cases regional, level so including any sub-national location data would be more than noise, but misleading.

**Comment by stevieflow** [comment]
It should be noted that it is entirely valid in the IATI standard to publish a ``location`` element **without** specific lat/long points 

There are some publishers who use location to restate the ``recipient-country`` data within the ``location`` element, because the location element is more useful to GIS specialists, given the way it is structured eg:

```
<location ref="UA">
<location-reach code="2"/>
<location-id code="UA" vocabulary="A4"/>
<name>
<narrative xml:lang="EN">Ukraine</narrative>
</name>
<administrative code="UA" vocabulary="A4"/>
</location>
<location>
```

(from this [randomly selected activity](http://d-portal.org/q.html?aid=XM-DAC-47066-DP.2114))

This data might _look_ meaningless, but it is valid in the schema, and there is a use case.

Secondly, the range of geographic things that can be described with the location element is wide ranging.  There are currently [662 types of locations](https://codelists.codeforiati.org/LocationType/), across [nine categories](https://codelists.codeforiati.org/LocationType-category/).  

This further highlights that the location function of the IATI standard is more attuned to interoperability with GIS systems, rather than simply giving a lat/long set of points.

Fully agree with points made with regards to exclusions, and on national projects.  The whole purpose of the location element in IATI seems to be fixated on it producing a "map with points on", which is just one limited use case.  It seems a misdirection for the ATI to continue with this single line of enquiry.

**Comment by ForeignCommonwealthDevelopmentOffice** [comment]
FCDO agrees with others above.   FCDO will only include sub national locations where it makes sense to do so, and will not in the case of sensitive situations, or where we are disbursing at country level to those then working at a sub national level.  We would then rely on partners to add this information, but only where appropriate.  Also this category only really applies to C and D aid types too.

**Comment by jzheng-79** [comment]
Agree with comments above, especially for IATI activities related to national programmes, which should be excluded from the this requirement. 
Please also clarify the rationale for decreasing weight for this indicator. As this is not included in the 2022 ATI methodology paper, please update the full weight table in order to better understand the impact of all the weight changes.

**Comment by publishwhatyoufund** [comment]
**@ToonVB, @AndieVaughn**: We have excluded aid types B01 and B02 from this test. B03 and B04 can be for specific purpose programs and funds, so could have a subnational location. We will exclude aid types F and H.  Aid types under category A could include a sub-national location - contributions could be to municipal or regional government budgets, for example. Likewise with technical assistance - this could be given to a local government entity or involve advice about activity in a specific region or district. I’m afraid the Index scoring approach would not allow us to award a full score for publishing a lower than full percentage of locations.

**@breidertmt:** redaction language for locations in Afghanistan and Burma will not be failed in our IATI sampling.

**@stevieflow**: We will not be changing the weighting of this indicator.

Half of the points for this indicator are scored based on the location narrative being completed, the other half are scored for publishing a lat/long point. Both of these types of location data are useful for different uses. 

Restating the recipient country in the location element may be useful but it doesn’t provide a subnational location which is the question asked for this indicator: “Does this organisation publish the sub-national geographic location for this activity?”

The subnational location information published and assessed against this indicator provides information about the location of activities in a country, which is useful for those monitoring aid projects in a country, beyond just producing a “map with points on”.

**Comment by publishwhatyoufund** [comment]
We will modify this test to exclude aid types F and H, debt relief and in-donor refugee costs.
