### ISSUE TITLE
Evaluations

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2022-Index-indicator-definitions#33]
## Description

Evaluation documents consider what the activity achieved, whether the intended objectives were met, what the major factors influencing the achievement or non-achievement of the objectives were and an assessment of the impact, effect and value of the activity.

This is only expected if the activity is in the completion or post-completion phase. 

This is not expected if the default aid type code is administrative costs (G01).

## Proposed test
```python
   For each current activity,
   i​f `activity-status/@code` i​s one of (3, 4)
   a​nd `default-aid-type/@code` i​s n​ot G01
   o​r `document-link/category[@code="A07"]` is present
   then `document-link/category[@code="A07"]` should be present
```

**Comment by breidertmt** [comment]
How will PWYF plan to take into account evaluations which have been redacted due to sensitivities for the health and safety of implementing partners or national security risks/interests, especially in light of the current situation in Afghanistan. The U.S. has standard redaction language which is used and allowable by law and it is in line with OECD/DAC decisions and to protect the security of our implementing partners, programs, and beneficiaries. The U.S. and other donors redact titles, descriptions, and implementing partner names (with the exception of PIOs) for Afghanistan and other sensitive areas e.g. Burma.  We are working internally with USG guidance and externally both with IATI and through our DAC delegate to establish guidance and best practices on how to move forward to balance transparency and sensitive data.

**Comment by AndieVaughn** [comment]
Some USAID activities by default will never have evaluations to publish. We propose excluding A01, B02, and B04 aid types or something similar to hone the test’s measurement of transparency. We proposed a similar change in the last review of methodology and maintain evaluations for core contributions, pooled funds, etc. cannot be accurately reported by donors who cannot track specific funds after disbursement.

**Comment by randymatthews** [comment]
How can evaluations done above the activity level, but meant to impact the activity level,  be taken into account?

**Comment by Melina-Loewer** [comment]
**On behalf of BMZ we would like to raise:** As we understand your criteria for Evaluations, this Indicator assesses every project, that has the activity status 3 or 4, i.e. is in the completion or post-completion phase. However, not all of our finalised or closed projects are published with an evaluation link, e.g. because a final evaluation of a project has not been composed (GIZ’s evaluation system: https://www.giz.de/en/downloads/GIZ_EVAL_EN_general%20description.pdf). However, every evaluation realized is made available in the IATI activity file on project level - meaning our data is de facto comprehensive. This was sanctioned in the last ATI round and we would be keen to see a fairer approach to this. 

Moreover, the drafting of an evaluation might take some time after a project has been closed. How exactly do you assess projects, that are finalized or closed, but haven’t yet composed a final evaluation? Is there for example a minimum period in which the report must be available?

**Comment by ForeignCommonwealthDevelopmentOffice** [comment]
Agree with Andie on proposed excluded codes.  FCDO has reviews of progress contained within annual reviews, project completion reports as well as documents specifically titled as evaluations at project not activity level.    We sometimes have evaluations within a programme as well as a project completion report just after, and an evaluation covering several programmes may occur later.    Re. breidertmt's comments on Afghanistan documentation, FCDO is also reviewing its data at the current time.

**Comment by publishwhatyoufund** [comment]
**@breidertmt**: publishers will not be penalised for security-related redactions in our IATI data quality sampling, and redacted documents or redaction text will be picked up and scored by our automated tests.

**@AndieVaughn, @ForeignCommonwealthDevelopmentOffice**: It would be too difficult to exclude specific activities from the evaluations test since there is unlikely to be a common approach across organisations in the Index. This goes for aid types A01, B02 and B04 for which some organisations may choose to produce evaluations or publish evaluations that have been produced by recipients.

**@randymatthews, @ForeignCommonwealthDevelopmentOffice**: For this indicator we would pass any evaluation published against an activity that includes an evaluation of that specific activity, even if this is part of a wider programme, sector or geographic evaluation.

**@Melina-Loewer:** we accept that not all organisations carry out formal evaluations for all of their activities. Please note that if interim evaluations are published for activities these will also be scored for this indicator, including if the activity is not yet completed.
